"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
# 'format = $all'
format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_state\
$git_status\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

# @theme:shk@
palette = 'shk'

[battery]
disabled = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"

[cmd_duration]
min_time = 1_000
show_milliseconds = true
#show_notifications = true
min_time_to_notify = 60_000

[directory]
truncation_symbol = '… '

[git_branch]
format = '[($remote_branch:)$branch]($style) '

[git_status]
stashed = '#'
modified = '~'
deleted = 'x'
ignore_submodules = true

[hostname]
ssh_only = true
ssh_symbol = ''
format = '[$ssh_symbol$hostname]($style)'

[jobs]
threshold = 1
symbol_threshold = 1
number_threshold = 1
symbol = '✦ '

[line_break]
disabled = false

[os]
disabled = true

[package]
disabled = true

# @theme:shk@
[palettes.shk]
black = '#000000'
red = '#ED1515'
green = '#11D116'
yellow = '#FF9400'
blue = '#0C48CC'
magenta = '#8C54FE'
cyan = '#1D99F3'
white = '#FFFFFF'

[shell]
disabled = true

[sudo]
disabled = false

[time]
disabled = true

[username]
show_always = false
