#!/usr/bin/env bash

command -v bash >/dev/null || exit 1

if ! command -v starship >/dev/null ; then
    command -v wget >/dev/null || exit 1
    wget --quiet https://starship.rs/install.sh -O - | bash
fi
if ! test -f ~/.bashrc.local ; then
    if command -v starship >/dev/null ; then
        echo "eval \"\$(starship init bash)\"" > ~/.bashrc.local
    fi
fi
if ! test -f ~/.zshrc.local ; then
    if command -v starship >/dev/null ; then
        echo "eval \"\$(starship init zsh)\"" > ~/.zshrc.local
    fi
fi

if ! test -d ~/.local/share/bash/preexec ; then
    if command -v git >/dev/null ; then
        git clone https://github.com/rcaloras/bash-preexec.git ~/.local/share/bash/preexec
    fi
fi

# EOF
