theme = "monokai_pro"

[editor]
scrolloff = 5
line-number = "absolute"
auto-format = true
auto-save = true
auto-pairs = false
cursorline = true
mouse = true
scroll-lines = 5
bufferline = "multiple"
insert-final-newline = true

[editor.search]
smart-case = false

[editor.whitespace]
all = "none"

[editor.soft-wrap]
enable = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode","spinner","version-control"]
center = ["read-only-indicator","file-base-name","file-modification-indicator","position","position-percentage"]
right = ["file-encoding","file-line-ending","file-type"]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"
#separator = "╎"

[keys.normal]
'~' = ":config-open"
r = ":reload"
R = ":reload-all"
i = "insert_mode"
a = "append_mode"
v = "select_mode"
c = "change_selection"
d = "delete_selection"
backspace = "delete_char_backward"
del = "delete_char_forward"
ret = "insert_newline"
esc = ["collapse_selection","keep_primary_selection"]
#left = "move_prev_long_word_end"
#right = "move_next_long_word_start"
C-a = ["goto_line_start","goto_first_nonwhitespace"]
C-e = "goto_line_end"
C-left = "goto_line_start"
C-right = ["goto_line_end","move_char_right"]
C-space = "command_palette"
C-up = "page_up"
C-S-up = "goto_file_start"
C-down = "page_down"
C-S-down = "goto_file_end"
S-up = ["select_mode","extend_line_up","exit_select_mode"]
S-down = ["select_mode","extend_line_down","exit_select_mode"]
S-left = ["select_mode","extend_char_left","exit_select_mode"]
S-right = ["select_mode","extend_char_right","exit_select_mode"]
C-S-left = ["select_mode","extend_to_line_start","exit_select_mode"]
C-S-right = ["select_mode","extend_to_line_end_newline","exit_select_mode"]
C-c = "yank_main_selection_to_primary_clipboard"
C-v = "paste_primary_clipboard_after"
#:sort	Sort ranges in selection.
#:rsort	Sort ranges in selection in reverse order.
[keys.normal.C-o]
f = "file_picker"
b = "buffer_picker"
n = ":new"
[keys.normal.C-b]
n = ":buffer-next"
p = ":buffer-previous"
[keys.normal.C-s]
s = ":write"
a = ":write-all"
[keys.normal.C-q]
b = ":buffer-close"
B = ":buffer-close-others"
a = ":buffer-close-all"
q = ":quit"
Q = ":quit!"

[keys.insert]
C-space = "command_palette"
C-backspace = "delete_word_backward"
C-del = "delete_word_forward"
C-f = "search"
C-F = "global_search"
'C-]' = "search_next"
'C-[' = "search_prev"
#C-t = "rename_symbol"
#C-u = "switch_to_uppercase"
#C-l = "switch_to_lowercase"
#'C-|' = ":pipe"
#'C-.' = "repeat_last_motion"

[keys.insert.g]
D = "goto_definition"
d = "goto_declaration"
i = "goto_implementation"
r = "goto_reference"
c = "goto_window_center"
l = "goto_line"

[keys.insert.C-s]
s = ":write"
a = ":write-all"

[keys.insert.C-z]
u = "undo"
r = "redo"
z = "suspend"

[keys.normal."+"]
m = ":run-shell-command make"

[keys.select]
f = "format_selections"
j = "join_selections"
l = "align_selections"

# :yank-join	Yank joined selections. A separator can be provided as first argument. Default value is newline.
# :clipboard-yank	Yank main selection into system clipboard.
# :clipboard-yank-join	Yank joined selections into system clipboard. A separator can be provided as first argument. Default value is newline.
# :primary-clipboard-yank	Yank main selection into system primary clipboard.
# :primary-clipboard-yank-join	Yank joined selections into system primary clipboard. A separator can be provided as first argument. Default value is newline.
# :clipboard-paste-after	Paste system clipboard after selections.
# :clipboard-paste-before	Paste system clipboard before selections.
# :clipboard-paste-replace	Replace selections with content of system clipboard.
# :primary-clipboard-paste-after	Paste primary clipboard after selections.
# :primary-clipboard-paste-before	Paste primary clipboard before selections.
# :primary-clipboard-paste-replace	Replace selections with content of system primary clipboard.
# :set-language, :lang	Set the language of current buffer (show current language if no value specified).
# :set-option, :set	Set a config option at runtime.
# :toggle-option, :toggle	Toggle a boolean config option at runtime.
# :get-option, :get	Get the current value of a config option.
# :reflow	Hard-wrap the current selection of lines to a given width.
# :insert-output	Run shell command, inserting output before each selection.
# :append-output	Run shell command, appending output after each selection.
