#!/bin/sh

echo "+-----------------------+"
echo "| shkschneider/dotfiles |"
echo "+-----------------------+"

# TODO move to .local along with backup

cd $(readlink -f -- $(dirname -- $0))
bak="$HOME/.config/backup"
[ -d "$bak" ] || mkdir -p "$bak"
if [ $# -eq 0 ] ; then
  # https://unix.stackexchange.com/a/137571
  # https://unix.stackexchange.com/a/358286
  set -- $(git ls-files -X .gitignore | grep -v '/.gitignore$' | grep -v '.md$' | grep -v dotfiles)
fi
echo $bak/
echo

i=0
e=0
for dotfile in "$@" ; do
  i=$((i + 1))
  printf '[%02d/%02d] %s … ' $i $# "$(tput rev)$dotfile$(tput sgr0)"
  if [ ! -e "./$dotfile" ] ; then
    printf "$(tput setaf 1)missing$(tput sgr0) ✖\n"
    e=$((e + 1))
    continue
  fi
  if [ ! -d "$(dirname "$HOME/$dotfile")" ] ; then
    mkdir -p "$(dirname "$HOME/$dotfile")" &>/dev/null
  fi
  if [ -e "$HOME/$dotfile" ] ; then
    printf 'exists '
    if [ -L "$HOME/$dotfile" ] ; then
      if [ "$(readlink -f $HOME/$dotfile)" == "$PWD/$dotfile" ] ; then
        printf "$(tput setaf 2)identical$(tput sgr0) ✔\n"
        continue
      else
        printf "$(tput setaf 3)conflict$(tput sgr0) "
        rm -f "$HOME/$dotfile" &>/dev/null
      fi
    else
      mv -f "$HOME/$dotfile" $bak/ &>/dev/null
      printf "$(tput setaf 4)saved$(tput sgr0) "
    fi
  else
    printf "$(tput setaf 3)missing$(tput sgr0) "
  fi
  ln -s "$PWD/$dotfile" "$HOME/$dotfile" &>/dev/null
  printf "$(tput setaf 2)linked$(tput sgr0) ✔\n"
done

echo
echo $bak/
echo "+---------------------------------------+"
echo "| So Long, and Thanks for All the Fish. |"
echo "+---------------------------------------+"

exit $e

# EOF
