#!/usr/bin/env bash

NAME="sysget"
DESCRIPTION="one package manager (wrapper) to rule them all"
VERSION="4.1.0"
# 4.2: continue, multi-commands...
# 4.1: fuzzy select
# 4.0: {/usr,~/.local}/share/pm/*.ini
# 3.3: sudo, debug
# 3.2: more methods (list, check, sources...)
# 3.1: configuration (~/.config/pm.conf)
# 3: if/else of binaries (apt, dnf, pacman, xbps, ...)
# 2: package managers as methods (dpkg, rpm)
# 1: huge switch/case (dpkg)
LC_ALL=C
LANG=C

PackageManager=$(false \
    || command -v apk \
    || command -v apt \
    || command -v dnf \
    || command -v pacman \
    || command -v xbps-install \
    || command -v zypper \
false)
PackageManager="${PackageManager##*/}"
if [ -z "$PackageManager" ] ; then
    echo "Unrecognized Package Manager" >&2
    exit 1
fi

help() {
    echo "$NAME -- $DESCRIPTION"
    echo -e "\t[-l|--list] [-v|--verbose]"
    echo -e "\t[-d|--dry-run] [-c|--continue]"
    echo -e "\t[command] [argument] ..."
}

version() {
    local PackageManager=$(command -v "$PackageManager" || echo "$PackageManager")
    local Version="$($PackageManager --version 2>/dev/null | grep -oP '[0-9]+(\.[0-9]+)+' | head -1)"
    echo "$NAME $VERSION > $PackageManager $Version"
}

OptDryRun=false
OptVerbose=false
OptContinue=false
while [ $# -gt 0 ] ; do
    case "$1" in
        "--help") help >&1 ; exit 0 ;;
        "--version") version >&1 ; exit 0 ;;
        "-d"|"--dry-run") shift ; OptDryRun=true ;;
        "-v"|"--verbose") shift ; OptVerbose=true ;;
        "-c"|"--continue") shift ; OptContinue=true ;;
        *) break ;;
    esac
done
[ "$OptVerbose" == "true" ] && version

inis=(
    "${XDG_DATA_HOME:-$HOME/.local/share}/$NAME"
    "/usr/share/$NAME"
    "."
)
for ini in ${inis[@]} ; do
    ini="$ini/${PackageManager/-*}.ini"
    [ -f "$ini" ] && break
done
if [ ! -f "$ini" ] ; then
    echo "No configuration file found for: '$PackageManager'" >&2
    for ini in ${inis[@]} ; do
        echo -e "\tin $ini" >&2
    done
    exit 1
fi
unset inis
[ "$OptVerbose" == "true" ] && echo "$ini"

run() {
    local Command="$1"
    Command="${Command# }"
    Command="${Command% }"
    shift
    local Lines=$(grep "^$Command=" "$ini" | cut -d'=' -f2- | head -1)
    if [ -z "$Lines" ] ; then
        echo "Unknown command: $Command" >&2
        help >&2
        exit 1
    fi
    if [[ "$Lines" =~ \.\.\. ]] ; then
        if [ $# -eq 0 ] ; then
            read -p "<<< ${PackageManager}(${Command/=*}) " Line
            Lines="${Lines/...}$Line"
        else
            [ "$OptVerbose" == "true" ] && echo "<<< $Command $@"
            Lines="${Lines/...}$@"
        fi
    elif [ $# -gt 0 ] ; then
        for Command in $Command $@ ; do
            run "$Command"
        done
        return
    else
        echo "<<< $Command $@"
    fi
    IFS=';' read -ra Lines <<< "$Lines"
    for Line in "${Lines[@]}"; do
        Line="${Line# }"
        Line="${Line% }"
        echo ">>> $Line"
        [ "$OptDryRun" == "true" ] && break
        if [ "$(whoami)" != "root" ] ; then
            sudo sh -c "$Line"
        else
            sh -c "$Line"
        fi
        [ "$OptContinue" == "true" -o $? -eq 0 ] || exit 1
    done
}

if [ $# -eq 0 ] ; then
    Command=$(
        cat "$ini" \
            | grep -v '^;' | grep '=' \
            | sort -u \
            | sed 's;=; = ;g' \
            | fzf --preview="$PackageManager --help 2>/dev/null"
    )
    if [ $? -eq 0 ] ; then
        run "${Command/ =*}"
        unset Command
    fi
elif [ "$1" == "--" ] ; then
    shift
    echo "<<< $@"
    echo ">>> $PackageManager $@"
    if [ "$OptDryRun" == "false" ] ; then
        $PackageManager $@
        exit $?
    fi
elif [ "$1" == "-l" -o "$1" == "--list" ] ; then
    if [ "$OptVerbose" == "true" ] ; then
        for ini in ${inis[@]} ; do
            echo "$ini"
        done
    fi
    cat "$ini" \
        | grep -v '^;' | grep '=' \
        | sort -u \
        | sed 's;=; = ;g'
else
    Command="$1"
    shift
    run "$Command" $@
    unset Command
fi

unset PackageManager
exit 0

# EOF
