#!/usr/bin/env bash

if command -v lite-xl >/dev/null ; then
    if command -v git >/dev/null ; then
        git clone https://github.com/lite-xl/lite-xl-plugins ~/.local/share/lite-xl-plugins
        test -d ~/.config/lite-xl/plugins || mkdir --parents ~/.config/lite-xl/plugins
        for plugin in bracketmatch.lua editorconfig ephemeral_tabs.lua gitstatus.lua restoretabs.lua sort.lua ; do
            cp -f ~/.local/share/lite-xl-plugins/$plugin ~/.config/lite-xl/plugins/
        done
        rm -rf ~/.local/share/lite-xl-plugins
    else
        echo "git: command not found" >&2
    fi
fi

if command -v nano >/dev/null ; then
    mkdir --parents ~/.local/share/nano
    if test -d /usr/share/nano ; then
        find /usr/share/nano -type f -name "*.nanorc" | xargs -i cp -f {} ~/.local/share/nano
    fi
    if command -v git >/dev/null ; then
        git clone https://github.com/scopatz/nanorc ~/.cache/nano
        find ~/.cache/nano -type f -name "*.nanorc" | xargs -i cp -f {} ~/.local/share/nano
        rm -rf ~/.cache/nano
    else
        echo "git: command not found" >&2
    fi
    if ! test -f ~/.nanorc ; then
        echo "set linenumbers" > ~/.nanorc
        find ~/.config/nano -type f -name "*.nanorc" | xargs -n1 basename \
            | xargs -I {} echo "include \"~/.config/nano/{}\"" >> ~/.nanorc
    fi
fi

if command -v micro >/dev/null ; then
    micro -plugin install editorconfig
    micro -plugin install filemanager
fi

# EOF
