#!/usr/bin/env bash

if command -v nano >/dev/null ; then
    mkdir --parents ~/.local/share/nano
    if test -d /usr/share/nano ; then
        find /usr/share/nano -type f -name "*.nanorc" | xargs -i cp -f {} ~/.local/share/nano
    fi
    if command -v git >/dev/null ; then
        git clone https://github.com/scopatz/nanorc ~/.cache/nano
        find ~/.cache/nano -type f -name "*.nanorc" | xargs -i cp -f {} ~/.local/share/nano
        rm -rf ~/.cache/nano
    else
        echo "git: command not found" >&2
    fi
    if ! test -f ~/.nanorc ; then
        echo "set linenumbers" > ~/.nanorc
        find ~/.config/nano -type f -name "*.nanorc" | xargs -n1 basename \
            | xargs -I {} echo "include \"~/.config/nano/{}\"" >> ~/.nanorc
    fi
fi

# EOF
