#!/usr/bin/env zsh
# ~/.config/zsh/rc

[[ -o interactive ]] || return 0

typeset -U fpath # no duplicates
if [[ -d "$HOME/.config/zsh/zfunctions" ]] ; then
    fpath=($HOME/.config/zsh/zfunctions $fpath)
    for zf in $(find "$HOME/.config/zsh/zfunctions" -maxdepth 1 2>/dev/null) ; do
        autoload -Uz "${zf:t:r}"
        unset zf
    done
    unset fpath
fi

for rc in $(find "$HOME/.config/zsh/" -name '*.zsh' 2>/dev/null) ; do
    [[ -r "$rc" ]] && source "$rc"
    unset rc
done

true # $?

# EOF
