# ~/.config/zsh/zshrc

source $HOME/.config/sh/shrc

[[ -o interactive ]] || return

#:modules

typeset -U fpath # no duplicates
if test -d $HOME/.config/zsh/zfunctions ; then
    fpath=($HOME/.config/zsh/zfunctions $fpath)
    for zf in $(find $HOME/.config/zsh/zfunctions -maxdepth 1 2>/dev/null) ; do
        autoload -Uz ${zf:t:r}
    done
fi

#:sources

for rc in $(find $HOME/.config/zsh -maxdepth 1 -name '*.zsh' 2>/dev/null) ; do
    source $rc
done

# EOF
