# ~/.tmux.conf

set -g @plugin 'tmux-plugins/tpm'

source-file ~/.tmux/plugins.conf
source-file ~/.tmux/options.conf
source-file ~/.tmux/bindings.conf
source-file ~/.tmux.conf.local

run '~/.tmux/plugins/tpm/tpm'

# EOF
