#!/usr/bin/env bash
# ~/.config/bash/rc

[[ $- != *i* ]] && return 0

for rc in $(find "$HOME/.config/bash/" -name '*.bash' 2>/dev/null) ; do
    [[ -r "$rc" ]] && . "$rc"
    unset rc
done

true # $?

# EOF
