# /etc/systemd/logind.conf.d/power.conf

[Login]
#SleepOperation=suspend-then-hibernate suspend
HandlePowerKey=ignore
HandlePowerKeyLongPress=poweroff
HandleRebootKey=ignore
HandleRebootKeyLongPress=reboot
HandleSuspendKey=ignore
HandleSuspendKeyLongPress=suspend
HandleHibernateKey=ignore
HandleHibernateKeyLongPress=hibernate
#WallMessages=yes

# EOF
