# /usr/share/keyd/keyd.conf

[ids]
*

[main]
capslock = leftshift
#leftshift = leftshift
#leftcontrol = leftcontrol
leftmeta = layer(alt)
leftalt = layer(meta)
#rightalt = layer(alt)
rightcontrol = middlemouse

# EOF
