# ~/.config/zsh/zshrc

source $HOME/.config/sh/shrc

[[ -o interactive ]] || return

export ZDOTDIR=${ZDOTDIR:-$HOME}
export ZCONFDIR=${ZCONFDIR:-$HOME/.config/zsh}

bindkey -e # emacs

# https://zsh.sourceforge.io/Doc/Release/Options.html

unsetopt beep list_beep hist_beep # stfu
unsetopt flow_control # suspend
unsetopt no_match
setopt clobber # override with redirects
setopt ignore_eof ; bindkey -r '^D' # exit
unsetopt rm_star_silent
setopt case_glob case_match # case-sensitives
setopt glob_complete # expand globbing
setopt interactive_comments

# path

typeset -U path # no duplicates

setopt hash_executables_only

type bin &>/dev/null || {
  bin() {
    type $@ &>/dev/null
  }
}

# fpath

typeset -U fpath # no duplicates

if [ -d $ZCONFDIR/zfunctions ] ; then
  fpath=($ZCONFDIR/zfunctions $fpath)
  while read rc ; do
    autoload -Uz ${rc:t:r}
  done < <(find $ZCONFDIR/zfunctions/* -maxdepth 1 2>/dev/null)
fi

# sources

while read rc ; do
  source $rc
done < <(find $ZCONFDIR/functions/*.zsh -maxdepth 1 2>/dev/null)

while read rc ; do
  source $rc
done < <(find $ZCONFDIR/*.zsh -maxdepth 1 2>/dev/null)

# EOF
