#!/usr/bin/env bash

_() {
    if ! command -v $1 ; then
        echo -n "$1: command not found"
        shift
        test $# -gt 0 && echo " -- $@"
    fi
}

### CLI

_ wget "https://www.gnu.org/software/wget/" # package for retrieving files using the most widely used internet protocols
_ curl "https://github.com/curl/curl" # ommand line tool and library for transferring data with url syntax

mkdir -p ~/.local/bin
if ! test -f ~/.local/bin/pipes ; then
    wget --quiet https://raw.githubusercontent.com/pipeseroni/pipes.sh/master/pipes.sh -O ~/.local/bin/pipes
fi
if ! test -x ~/.local/bin/pipes ; then
    chmod a+x ~/.local/bin/pipes
fi

_ git "https://github.com/gitgitgadget/git" # distributed version control system
if command -v git >/dev/null ; then
    _ lazygit "https://github.com/jesseduffield/lazygit" # terminal ui for git commands
    if command -v fzf >/dev/null ; then
        # https://github.com/junegunn/fzf
        if ! test -f ~/.config/sh/fzf-git.sh ; then
            test -d ~/.config/sh || mkdir -p ~/.config/sh
            wget --quiet https://raw.githubusercontent.com/junegunn/fzf-git.sh/main/fzf-git.sh -O ~/.config/sh/fzf-git.sh
            source ~/.config/sh/fzf-git.sh
            echo "#source ~/.config/sh/fzf-git.sh"
            echo "#alias git-fuzzy-files=_fzf_git_files"
            echo "#alias git-fuzzy-branches=_fzf_git_branches"
            echo "#alias git-fuzzy-tags=_fzf_git_tags"
            echo "#alias git-fuzzy-hashes=_fzf_git_hashes"
        fi
    fi
    # https://github.com/jwiegley/git-scripts
    if ! test -d ~/.config/git/scripts ; then
        test -d ~/.config/git || mkdir -p ~/.config/git
        git clone https://github.com/jwiegley/git-scripts.git ~/.config/git/scripts
        find ~/.config/git/scripts -maxdepth 1 -type f -name "git-*"
    fi
fi

_ kew "https://github.com/ravachol/kew" # command-line music player
if command -v kew >/dev/null ; then
    kew path "${XDG_MUSIC_DIR:-$HOME/Music}"
fi

_ acpi "https://sourceforge.net/projects/acpiclient/files/acpiclient/" # battery and thermal information
_ bat "https://github.com/sharkdp/bat" # a cat(1) clone with wings
_ batsignal "https://github.com/electrickite/batsignal" # lightweight battery daemon -- notifies
_ bluetuith "https://github.com/darkhz/bluetuith" # tui bluetooth manager
_ btm "https://github.com/ClementTsang/bottom" # cross-platform graphical process/system monitor
_ cava "https://github.com/karlstav/cava" # cross-platform audio visualizer
_ cheat "https://github.com/cheat/cheat" # cheatsheets on the command-line
_ cool-retro-term "https://github.com/Swordfish90/cool-retro-term" # mimics the old cathode display
_ docker "https://github.com/docker/docker" # pack, ship and run any application as a lightweight container
_ dtrx "https://github.com/moonpyk/dtrx" # intelligent archive extraction
_ duf "https://github.com/muesli/duf" # better df(1) alternative
_ entr "https://github.com/eradman/entr" # run arbitrary commands when files change
#_ exa "https://github.com/ogham/exa" # modern replacement for ls(1)
_ eza "https://github.com/eza-community/eza" # modern and maintained replacement for ls(1)
_ fastfetch "https://github.com/fastfetch-cli/fastfetch" # like neofetch but much faster
_ fd "https://github.com/sharkdp/fd" # a simple, fast and user-friendly alternative to find(1)
_ fff "https://github.com/dylanaraps/fff" # simple file manager written in bash
_ fzf "https://github.com/junegunn/fzf" # a command-line fuzzy finder
#_ fzy "https://github.com/jhawthorn/fzy" # fuzzy finder for the terminal
_ ghfetch "https://github.com/mrshmllow/ghfetch" # neofetch for githu
_ glances "https://github.com/nicolargo/glances" # glances an eye on your system
- glow "https://github.com/charmbracelet/glow" # render markdown on the cli
_ gron "https://github.com/tomnomnom/gron" # make json greppable
_ httpie "https://github.com/httpie/cli" # modern, user-friendly command-line http client for the api era
_ hyperfine "https://github.com/sharkdp/hyperfine" # command-line benchmarking tool
_ jq "https://github.com/jqlang/jq" # command-line json processor
_ lf "https://github.com/gokcehan/lf" # terminal file manager
_ mtr "https://github.com/traviscross/mtr" # network diagnostic tool (ping/traceroute)
_ nb "https://github.com/xwmx/nb" # local plain text note‑taking
_ pdu "https://github.com/KSXGitHub/parallel-disk-usage" # blazing fast directory tree analyzer
_ procs "https://github.com/dalance/procs" # modern replacement for ps
_ progress "https://github.com/Xfennec/progress" # linux tool to show progress for cp, mv, dd, ...
_ redshift "https://github.com/jonls/redshift" # adjusts the color temperature of your screen according to your surroundings
_ rg "https://github.com/BurntSushi/ripgrep" # ripgrep recursively searches directories for a regex pattern while respecting your gitignore
_ sd "https://github.com/chmin/sd" # intuitive sed(1) alternative
_ slides "https://github.com/maaslalani/slides" # terminal based presentation tool
#_ so "https://github.com/samtay/so" # terminal interface for Stack Overflow
_ spark "https://github.com/holman/spark" # generates sparklines for a set of data
_ tldr "https://github.com/tldr-pages/tldr" # collaborative cheatsheets for console commands
_ tuc "https://github.com/riquito/tuc" # when cut(1) doesn't cut it
_ viu "https://github.com/atanunq/viu" # terminal image viewer
#_ xxh "https://github.com/xxh/xxh" # bring your favorite shell wherever you go through the ssh
_ yq "https://github.com/mikefarah/yq" # portable command-line yaml, json, xml, csv, toml and properties processor
_ z "https://github.com/rupa/z" # jump around

### Editors

if command -v lite-xl >/dev/null ; then
    if command -v git >/dev/null ; then
        git clone https://github.com/lite-xl/lite-xl-plugins ~/.local/share/lite-xl-plugins
        test -d ~/.config/lite-xl/plugins || mkdir --parents ~/.config/lite-xl/plugins
        for plugin in bracketmatch.lua editorconfig ephemeral_tabs.lua gitstatus.lua restoretabs.lua sort.lua ; do
            cp -f ~/.local/share/lite-xl-plugins/$plugin ~/.config/lite-xl/plugins/
        done
        rm -rf ~/.local/share/lite-xl-plugins
    else
        echo "git: command not found" >&2
    fi
fi

if command -v helix >/dev/null ; then
	echo "..." >/dev/null
fi

if command -v micro >/dev/null ; then
    micro -plugin install editorconfig
    micro -plugin install filemanager
fi

if command -v nano >/dev/null ; then
    mkdir --parents ~/.local/share/nano
    if test -d /usr/share/nano ; then
        find /usr/share/nano -type f -name "*.nanorc" | xargs -i cp -f {} ~/.local/share/nano
    fi
    if command -v git >/dev/null ; then
        git clone https://github.com/scopatz/nanorc ~/.cache/nano
        find ~/.cache/nano -type f -name "*.nanorc" | xargs -i cp -f {} ~/.local/share/nano
        rm -rf ~/.cache/nano
    else
        echo "git: command not found" >&2
    fi
    if ! test -f ~/.nanorc ; then
        echo "set linenumbers" > ~/.nanorc
        find ~/.config/nano -type f -name "*.nanorc" | xargs -n1 basename \
            | xargs -I {} echo "include \"~/.config/nano/{}\"" >> ~/.nanorc
    fi
fi

if command -v emacs >/dev/null ; then
    if ! test -d ~/.emacs.d ; then
        if command -v git >/dev/null ; then
            git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
        else
            echo "git: command not found" >&2
        fi
    fi
fi

if command -v nvim >/dev/null ; then
    if ! test -d ~/.config/nvim ; then
        if command -v git >/dev/null ; then
            git clone https://github.com/LazyVim/starter ~/.config/nvim
        else
            echo "git: command not found" >&2
        fi
    fi
fi

### Shells

if ! command -v starship >/dev/null ; then
    command -v wget >/dev/null || exit 1
    wget --quiet https://starship.rs/install.sh -O - | bash
fi
if ! test -f ~/.bashrc.local ; then
    if command -v starship >/dev/null ; then
        echo "eval \"\$(starship init bash)\"" > ~/.bashrc.local
    fi
fi
if ! test -f ~/.zshrc.local ; then
    if command -v starship >/dev/null ; then
        echo "eval \"\$(starship init zsh)\"" > ~/.zshrc.local
    fi
fi

if ! test -d ~/.local/share/bash/preexec ; then
    if command -v git >/dev/null ; then
        git clone https://github.com/rcaloras/bash-preexec.git ~/.local/share/bash/preexec
    fi
fi

### Terminals

if ! test -f ~/.config/tmux/tmux.conf ; then
    test -d ~/.config/tmux || mkdir -p ~/.config/tmux
    wget --quiet https://raw.githubusercontent.com/gpakosz/.tmux/master/.tmux.conf -O ~/.config/tmux/tmux.conf
fi
if ! test -d ~/.config/tmux/tpm ; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    bash ~/.tmux/plugins/tpm/scripts/install_plugins.sh
    test -f ~/.tmux.conf.local || touch ~/.tmux.conf.local
fi

# alacritty >= 0.13.0
if test -f ~/.config/alacritty/alacritty.toml ; then
    if ! test -d ~/.config/alacritty/themes ; then
        git clone https://github.com/alacritty/alacritty-theme ~/.cache/alacritty-themes
        mv ~/.cache/alacritty-themes ~/.config/alacritty/themes
        rm -rf ~/.cache/alacritty-themes
    fi
    #import = [ "~/.config/alacritty/themes/${THEME:-afterglow}.toml" ]'
fi

#test -d ~/.config/tmux/tpm && run '~/.config/tmux/tpm/tpm'

### Miscellaneous

command -v vlc >/dev/null || echo "vlc: command not found" >&2

if command -v batsignal >/dev/null ; then
    if command -v systemctl >/dev/null ; then
        systemctl --user enable batsignal
        systemctl --user start batsignal
        if test -f ~/.config/systemd/user/batsignal.service.d/options.conf ; then
            mkdir --parents ~/.config/systemd/user/batsignal.service.d
            printf "[Service]\nExecStart=batsignal -d 5 -c 10 -w 20\n" \
                > ~/.config/systemd/user/batsignal.service.d/options.conf
        fi
    fi
fi

if ! test -d "${XDG_PICTURES_DIR:-$HOME/Pictures}/Wallpapers" ; then
    if command -v git >/dev/null ; then
        git clone https://github.com/LinuxKits/Distro-wallpapers.git ${XDG_PICTURES_DIR:-$HOME/Pictures}/Wallpapers
    else
        echo "git: command not found" >&2
    fi
fi

command -v ldm >/dev/null || echo "https://github.com/LemonBoy/ldm" >&2

command -v mkfs.vfat >/dev/null || echo "E: dosfstools!" >&2

# EOF
