# ~/.config/bash/bashrc

# If not running interactively, don't do anything
[ -z "$PS1" ] && return 0

BASHCONFDIR=${BASHCONFDIR:-$HOME/.config/bash}

# Options
if [ -x "$(which stty)" ] ; then
    stty -ixon 2>/dev/null
    stty -ixoff 2>/dev/null
fi
if [ -x "$(which xset)" ] ; then
    xset -dpms 2>/dev/null
    xset s off 2>/dev/null
fi
#set -o noclobber
set -o emacs
set -o ignoreeof
#shopt -s autocd
shopt -s hostcomplete
shopt -s cdspell
shopt -s histappend
shopt -s checkwinsize
shopt -s dotglob
shopt -s checkhash

case $OSTYPE in
  darwin*)
    SHELL_SESSION_HISTORY=0
    ;;
esac

# source

for rc in $BASHCONFDIR/functions/*.bash ; do
  source $rc
done

for rc in $BASHCONFDIR/*.bash ; do
  source $rc
done

for rc in $HOME/.bashrc.* ; do
  source $rc
done

# EOF
