# ~/.config/hypr/_exec.conf

exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start hyprpolkitagent

exec = ~/.local/bin/wallpaper
exec-once = waybar &
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent &
exec-once = dunst &
exec-once = LC_ALL=C.UTF-8 copyq --start-server enable
exec-once = hyprsunset &
exec-once = hypridle &

# EOF
