# ~/.config/hypr/_theme.conf

# @theme@
$font = sans-serif
$theme = Graphite-Dark
$cursor = Vimix
env = GTK_THEME, $theme
exec-once = gsettings set org.gnome.desktop.interface font-name "$font 11"
#exec-once = gsettings set org.gnome.desktop.interface gtk-theme "$theme"
#exec-once = gsettings set org.gnome.desktop.interface cursor-theme "$cursor"
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = hyprctl setcursor $cursor 24

# @theme@
general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1
    resize_on_border = false
    allow_tearing = false
    layout = dwindle # master
    col.active_border = rgba(eeeeeeaa)
    col.inactive_border = rgba(333333aa)
}

misc {
    font_family = sans-serif
    splash_font_family = sans-serif
}

decoration {
    rounding = 8
    active_opacity = 1.0
    inactive_opacity = 0.66
    shadow {
        enabled = false
    }
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
    }
}

# EOF
