# ~/.config/hypr/_workspace.conf

workspace = 1, on-created-empty:brave
workspace = 2, on-created-empty:kitty

workspace = special:special, on-created-empty:kitty
workspace = special:special, animations:enabled:0, general:gapsin:64, general:gapsout:64

bind = $mod, 0, togglespecialworkspace, special
bind = $mod Ctrl, 0, movetoworkspace, special:special

# EOF
