# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session || pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout = 600 #10m
    on-timeout = brightnessctl set 10% -s || hyprctl dispatch dpms off
    on-resume = brightnessctl -r || hyprctl dispatch dpms on
}

listener {
    timeout = 3600 #60m
    on-timeout = systemctl suspend
}

# EOF
