# ~/.config/hypr/hyprtoolkit.conf

background = 0xff333333
base = 0xff333333
text = 0xffeeeeee
accent = 0xff1793d1
font_family = JetBrains Mono
font_family_monospace = JetBrains Mono
rounding_large = 16
rounding_small = 8

# EOF
