# ~/.config/hypr/hyprsunset.conf

max-gamma = 150
profile { time = 6:00 identity = true gamma = 1.0 }
profile { time = 18:00 temperature = 5500 gamma = 0.8 }
profile { time = 23:00 temperature = 4000 gamma = 0.7 }

# EOF
