# ~/.config/hypr/hyprlock.conf

general {
    disable_loading_bar = true
    font_family = sans-serif
    grace = 0
    hide_cursor = true
    ignore_empty_input = true
    no_fade_in = false
    no_fade_out = false
}

animations {
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
    bezier = linear, 1, 1, 0, 0
    enabled = true
}

background {
    blur_passes = 3
    color = rgb(000000) # fallback
    monitor =
    path = screenshot
}

label {
    font_size = 25
    halign = center
    monitor =
    position = 0, -10
    text = cmd[] echo "$(whoami) @ $(uname -n)"
    valign = top
}

label {
    monitor =
    text = cmd[update:360000] date +'%d/%m/%+4Y'
    font_size = 50
    halign = center
    valign = center
    position = 0, 200
}

label {
    font_size = 100
    halign = center
    monitor =
    position = 0, 100
    text = cmd[update:1000] date +'%T'
    valign = center
}

input-field {
    check_color = rgb(ffd866)
    dots_size = 0.4
    dots_spacing = 0.3
    dots_text_format = *
    fade_on_empty = false
    fail_color = rgb(ff6188)
    fail_text = $FAIL
    font_color = rgb(eeeeee)
    halign = center
    inner_color = rgb(333333)
    monitor =
    outer_color = rgb(1793d1)
    outline_thickness = 2
    placeholder_text = _
    position = 0, -50
    rounding = 8
    size = 20%, 5%
    valign = center
}

label {
    font_size = 25
    halign = center
    monitor =
    position = 0, 10
    text = cmd[update:60000] printf "%d%% %s\n" "$(< /sys/class/power_supply/BAT0/capacity)" "$(tr '[A-Z]' '[a-z]' < /sys/class/power_supply/BAT0/status)"
    valign = bottom
}

# EOF
