# ~/.config/hypr/hyprtoolkit.conf

# @theme@
background = 0xff333333
base = 0xff333333
text = 0xffeeeeee
accent = 0xff1793d1

font_family = sans-serif
font_family_monospace = monospace
rounding_large = 16
rounding_small = 8

# EOF
