# ~/.config/hypr/_input.conf

input {
    #kb_layout = us
    follow_mouse = 0
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    touchpad {
        disable_while_typing = true
        natural_scroll = false
        #middle_button_emulation = true
    }
}

# EOF
