# ~/.config/hypr/_laptop.conf

monitor=,preferred@60,auto,1

animations {
    enabled = yes
}

decoration {
    shadow {
        enabled = false
    }
    blur {
        enabled = false
    }
}

misc {
    vfr = true
    vrr = false
}

gesture = 3, horizontal, workspace
bindl = , switch:off:Lid Switch, exec, hyprlock --immediate
#bindl = , switch:off:Lid Switch, exec, hyprctl dispatch dpms on
#bindl = , switch:on:Lid Switch, exec, hyprctl dispatch dpms off

# EOF
