# ~/.config/hypr/hyprlock.conf

general {
    hide_cursor = true
    ignore_empty_input = true
    grace = 0
    no_fade_in = false
    no_fade_out = false
    disable_loading_bar = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    color = rgb(000000) # fallback
}

label {
    monitor =
    text = cmd[] echo "$(whoami) @ $(uname -n)"
    font_size = 25
    font_family = JetBrains Mono
    halign = center
    valign = top
    position = 0, -10
}

label {
    monitor =
    text = cmd[update:360000] date +%x
    font_size = 50
    font_family = JetBrains Mono
    halign = center
    valign = center
    position = 0, 200
}

label {
    monitor =
    text = cmd[update:1000] date +%T
    font_size = 100
    font_family = JetBrains Mono
    halign = center
    valign = center
    position = 0, 100
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgb(333333)
    outer_color = rgb(1793d1)
    check_color = rgb(ffd866)
    fail_color = rgb(ff6188)
    font_color = rgb(eeeeee)
    fade_on_empty = false
    rounding = 8
    font_family = JetBrains Mono
    placeholder_text = _
    fail_text = $FAIL
    dots_text_format = *
    dots_size = 0.4
    dots_spacing = 0.3
    position = 0, -50
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] printf "%d%% %s\n" "$(< /sys/class/power_supply/BAT0/capacity)" "$(tr '[A-Z]' '[a-z]' < /sys/class/power_supply/BAT0/status)"
    font_size = 25
    font_family = JetBrains Mono
    halign = center
    valign = bottom
    position = 0, 10
}

# EOF
