#import = [ "~/.config/alacritty/themes/afterglow.toml" ]
live_config_reload = true

[bell]
animation = "Linear"
color = "#FCFCFC"
duration = 1

[colors]
draw_bold_text_with_bright_colors = true
[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"
[colors.selection]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
blink_interval = 500
[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 11
[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"
[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"
[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"
[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[window]
blur = false
decorations = "None"
decorations_theme_variant = "Dark"
dynamic_title = true
opacity = 0.85
startup_mode = "Maximized"
[window.dimensions]
columns = 0
lines = 0
