# ~/.tmux/bindings.conf

unbind Alt-b
unbind Space
set -g prefix Alt-Space
bind Alt-Space send-prefix

bind      R source-file ~/.tmux.conf \; display 'Reloaded'

bind      \` clock-mode
bind      / command-prompt
bind      $ command-prompt -p "run$" "run-shell '%%'"
bind      S command-prompt -p "save-buffer-to:" -I "~/" "capture-pane -S - ; save-buffer '%%' ; delete-buffer"
unbind    d
unbind    D
bind      Z detach-client

bind    Tab choose-tree

bind      T new # session
bind      Q kill-session

bind      t new-window
unbind   \"
bind      | split-window -h -c "#{pane_current_path}"
unbind    %
bind      _ split-window -v -c "#{pane_current_path}"
unbind    p
bind      , previous-window
unbind    n
bind      . next-window
bind      - last-window
unbind   \{
bind     \{ swap-window -t -1 \; select-window -t -1
unbind   \}
bind     \} swap-window -t +1 \; select-window -t +1
bind      q kill-window

bind     \\ display-panes
bind      @ choose-window 'join-pane -h -t "%%"'
bind      ! break-pane
bind   Left resize-pane -L
bind   Down resize-pane -D
bind     Up resize-pane -U
bind  Right resize-pane -R
bind -n M-L select-pane -L
bind -n M-R select-pane -R
bind -n M-U select-pane -U
bind -n M-D select-pane -D
unbind   \[
bind     \[ swap-pane -U
unbind   \]
bind     \] swap-pane -D
bind      z resize-pane -Z
unbind    x
bind      w kill-pane

# EOF
