# ~/.tmux/options.conf

set -g  clock-mode-colour red
set -g  visual-bell on

set -g  base-index 1
set -g  focus-events on
set -g  pane-base-index 1
set -g  renumber-windows on
set -s  escape-time 0

set -gw window-status-separator " | "
set -gw history-limit 65535

set -g  status on
set -g  status-position bottom
set -g  status-left '[#S] '
set -g  status-right '#h %R'
set -g  pane-active-border-style fg=yellow
set -g  pane-border-style fg=black
set -g  message-style bg=black,fg=white
set -gw window-status-current-format "#I#F#W"
set -gw window-status-format "#I#F#W"

# EOF
