# ~/.tmux/plugins.conf
#set -g @plugin 'tmux-plugins/tpm'
bind I run-shell 'bash ~/.tmux/plugins/tpm/scripts/install_plugins.sh'
bind U run-shell 'bash ~/.tmux/plugins/tpm/scripts/update_plugin.sh'

set -g  @plugin 'tmux-plugins/tmux-sensible'

set -g  @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g  @prefix_highlight_fg 'black'
set -g  @prefix_highlight_bg 'white'

set -g  @plugin 'seebi/tmux-colors-solarized'
set -g  @colors-solarized 'dark'
set -sa terminal-overrides ",xterm*:Tc"

# run '~/.tmux/plugins/tpm/tpm'
# EOF
