#!/usr/bin/env bash
# /usr/local/etc/bash/rc

[[ $- != *i* ]] && return 0

for rc in $(find "/usr/local/etc/bash/" -name '*.bash' 2>/dev/null) ; do
    [[ -r "$rc" ]] && source "$rc"
    unset rc
done

true # $?

# EOF
